-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 02-03-2021 a las 19:15:32
-- Versión del servidor: 10.4.17-MariaDB
-- Versión de PHP: 8.0.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `hcanime_anime`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `animes`
--

CREATE TABLE `animes` (
  `id_anime` int(11) NOT NULL,
  `imagen` varchar(100) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `titulo` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `descripcion` varchar(10000) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `fecha` varchar(30) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `estado` varchar(20) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `fondo` varchar(100) CHARACTER SET utf8 COLLATE utf8_spanish_ci NOT NULL,
  `temporada` int(2) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

--
-- Volcado de datos para la tabla `animes`
--

INSERT INTO `animes` (`id_anime`, `imagen`, `titulo`, `descripcion`, `fecha`, `estado`, `fondo`, `temporada`) VALUES
(19, 'KwZy08.jpg', 'Shin Chan ', 'Shin-chan es un manga habitual de yoshito usui manga, y una serie animada, sobre la vida de Shinnosuke Nohara, un niño particularmente travieso de cinco años. El manga no está terminado, debido a la muerte de su autor en 2009.', '2009', 'Finalizado', 'thumb-350-1092633.png', 1),
(20, 'trinity.jpg', 'Trinity Seven', 'En esta \"comedia romantica pero a veces seria historia de la escuela magica\", la vida como Arata Kasuga sabe que es aniquilada por un extrano incidente conocido como \"Fenomeno de Colapso\", que causa destruccion mundial y lleva a su primo Hijiri Kasuga al siguiente mundo. Para resolver el \"Fenomeno colapso\" y traer de vuelta a Hijiri, Arata se inscribe en la Royal Biblia Academy. Esperando en la escuela son siete hermosas mujeres usuarias de magia-La Trinidad Siete.', '2014', 'Finalizado', 'wp3714253.jpg', 1),
(34, 'nanatsu.jpg', 'Nanatsu No Taizai', 'Los Siete Pecados Capitales, un grupo de caballeros malignos que conspiraron para derrocar al Reino de Britania, se dice que fueron erradicados por los Caballeros Sagrados, aunque algunos dicen que aún viven. Diez años después, los Caballeros Sagrados dieron un golpe de estado y asesinaron al rey, convirtiéndose en los nuevos y tiránicos regidores del reino.', '2014', 'Finalizado', 'nanatsubg.jpg', 1),
(35, 'nanatsu2.jpg', 'Nanatsu no Taizai: Imashime no Fukkatsu', 'Segunda temporada de Nanatsu No Taizai, donde los 10 Mandamientos hacen su apariciendo en la Britania Antigua, podran los 7 Pecados Capitales hacerles Frente?', '2016', 'Finalizado', 'nanatsubg2.jpg', 2),
(23, '1603038436333.png', 'One Punch Man ', 'La historia tiene lugar en una metrópolis ficticia conocida como Ciudad Z, en Japón. El mundo se ve invadido por extraños monstruos que aparecen misteriosamente y que causan numerosos desastres a la población. Saitama es un poderoso superhéroe calvo que derrota fácilmente a los monstruos u otros villanos con un Único golpe de su puño. Debido a esto, Saitama ha encontrado aburrida su fuerza y siempre esta tratando de encontrar rivales mas poderosos que le puedan igualar.', '2015', 'Finalizado', '1603038459796.png', 1),
(32, 'Absolute.jpg', 'Absolute Duo', 'Toru Kokonoe se inscribe en Koryo Academy, una escuela secundaria donde sus estudiantes luchan entre si­ con armas conocidas como Blaze, como entrenamiento para convertirse en futuras fuerzas de paz. Los estudiantes deben pasar una batalla durante la ceremonia de calificación del día de primer año para poder inscribirse en la academia. Aunque la mayoría de los estudiantes manifiestan sus Blazes como armas cuerpo a cuerpo, la habilidad de Tor se manifiesta como un escudo, lo que lo convierte en un Irregular. La escuela utiliza un sistema Duo especial en el que a los estudiantes se les asignan socios. Tor está emparejado con Julie Sigtuna, una chica de pelo plateado de Escandinavia, y debe compartir una habitación con ella.', '2014', 'Finalizado', 'absolutebg.jpg', 1),
(25, 'fma1.jpg', 'Fullmetal Alchemist', 'Tras perder a su madre, Alphonse y Edward Elric tratan de revivirla usando la ciencia prohibida de la alquimia humana. Sin embargo, la alquimia opera bajo la teoría del cambio equivalente y romper el taba de la alquimia humana acarrea un alto precio. Ed pierde una de sus piernas y Al su cuerpo. Ed logra sellar el alma de Al dentro de una gran armadura, a costa de su brazo. años después, Ed (ahora con dos extremidades mecánicas) y Al (aún atrapado en la armadura) dejan su casa de la niñez, cada uno preocupado por la felicidad del otro. Ed, quien tuvo un talento y habilidad natural para la alquimia, se convierte en un alquimista con certificado nacional y pronto es conocido en todas partes como el ?Alquimista Full metal?. El verdadero objetivo de ambos hermanos es buscar cualquier informaciÃ³n sobre la legendaria Piedra Filosofal, con la esperanza de que Ésta les permita recobrar sus cuerpos. Todas sus esperanzas descansan en la mítica piedra, que incluso puede no existir.', '2010', 'Finalizado', '108065.jpg', 1),
(26, '491828.jpg', 'Fullmetal Alchemist: Brotherhood', 'La historia se centra en dos hermanos, Edward Elric y Alphonse Elric que rompieron el mayor taba de la alquimia, la trasmutación humana al tratar de revivir a su fallecida madre; en consecuencia Edward pierde su pierna izquierda y Alphonse pierde todo su cuerpo, Edward para salvar a su hermano sella su alma en una gran armadura de hierro a cambio de su brazo derecho; ahora los dos con un nuevo objetivo buscan desesperadamente la piedra filosofal para poder regresar sus cuerpos a la normalidad...', '2011', 'Finalizado', '108065.jpg', 2),
(27, 'wp4256906-min.jpg', 'Rakudai Kishi No Cavalry', 'La historia gira en torno a los Caballeros Mágicos, usuarios modernos de la magia que luchan con sus propias almas convertidas en armas. Ikki Kurogane asiste al colegio de estos caballeros, pero resulta ser el caballero fallido o el peor caballero que esta fracasando por no tener habilidades mágicas. Sin embargo, un día es retado a duelo por Stella, una princesa extranjera y la estudiante número uno del colegio. En este duelo, el perdedor tiene que ser obediente hacia el que gane por el resto de su vida.', '2015', 'Finalizado', 'wp2288707-rakudai-kishi-no-cavalry-wallpapers (1)-min.png', 1),
(28, 'Date.jpg', 'Date A Live', 'Itsuka Shidou es un estudiante de instituto que, durante las vacaciones, vive en primera persona un suceso sin igual. Ante Él aparece una chica con armadura, que destruye la ciudad que tiene delante. La chica responde ante el nombre de Tooka, y según la hermana de Shidou, es un espíritu, los cuales causaron un terremoto espacio-temporal 30 años atrás. La hermana de Shidou revela que su verdadera identidad es la de la líder de la organización Ratatosk y le cuenta a Shidou que la Única manera que tienen de salvar el mundo es hacer que Tooka se acabe enamorando de Él y tengan una cita.', '2013', 'Finalizado', 'fondo1.jpg', 1),
(30, 'date2.jpg', 'Date A Live II', 'Hace treinta años un fenómeno llamado Terremoto espacial devasto el centro de Eurasia, llevándose consigo la vida de al menos 150 millones de personas. Desde entonces, terremotos espaciales se han ido manifestando alrededor del mundo. Shido Itsuka, un estudiante de secundaria aparentemente normal se encuentra con una chica en el epicentro de un terremoto espacial y es informado por su hermana Kotori que esta chica es uno de los espiritus que causan los terremotos espaciales cuando estos aparecen en el mundo. Tambien se entera que su hermana es la capitana de la nave Ratatoskr y quien lo recluta para hacer uso de su misteriosa habilidad para sellar los poderes de los espiritus y evitar que se vuelvan una amenaza para la humanidad. Sin embargo, hay un inconveniente: para sellar un EspÃ­ritu, debe hacer que se enamore de Él.', '2014', 'Finalizado', 'fondo2.jpg', 2),
(33, 're.jpg', 'Re:Zero', 'En la historia, Subaru Natsuki es un estudiante corriente de instituto que se pierde en un mundo alternativo, donde una preciosa chica de pelo plateado lo rescata. Para devolverle el favor decide quedarse con ella, pero el destino con el que carga la muchacha es mucho más pesado de lo que Subaru puede imaginar. Los enemigos atacan sin descanso, uno tras otro, hasta que finalmente mueren tanto el como la chica. Es entonces cuando Subaru descubre que tiene el poder de dar marcha atrás en el tiempo y volver al inicio de la historia, al punto en el que llego al mundo desconocido. El problema es que el es el Único que recuerda lo ocurrido.', '2016', 'Finalizado', 'zero.jpg', 1),
(36, 'nanatsu3ra.jpg', 'Nanatsu no Taizai: Kamigami no Gekirin', 'War of the Gods, Despues de la caida de Camelot ante los 10 Mandamientos Britania esta luchando contra las grandes ordas de demonios que atacan sin sesar a todos los pueblos, pero aun hay una luz de esperanza, los 7 pecados capitales hacen su apariciendo derrotando decenas de demonios y liberando una gran parte del reino.', '2020', 'Finalizado', 'nanatsubg3.jpg', 3),
(37, '972957.jpg', 'Tokyo Ghoul', 'Extraños asesinatos se están sucediendo uno tras otro en Tokyo. Debido a las pruebas encontradas en las escenas, la policía concluye que los ataques son obra de ghouls que se comen a las personas. Kaneki y Hide, dos compañeros de clase, llegan a la conclusión de que si nadie ha visto nunca a esos necrófagos es porque toman la apariencia de seres humanos para ocultarse. Poco sabían entonces de que su teoría será más cierta de lo que pensaban cuando Kaneki es herido de gravedad por un monstruo y comienza a atraerle cada vez más la carne humana', '2014', 'Finalizado', 't.jpg', 1),
(38, 'fondo-img.jpeg', 'School Days', 'Argumento. Makoto viaja a la escuela en tren todos los di­as. ... Su compañera de mesa, Sekai Saionji, observa la foto durante una clase y se compromete a ayudarlo en concretar una relación amorosa con Kotonoha, a pesar del hecho de que, aunque Makoto no lo sabe, Sekai esa enamorada de el.', '2007', 'Finalizado', 'Fondo-baner.jpeg', 1),
(39, '1603262716495_compress95.jpg', 'Another', 'En 1972, un popular y carismático estudiante llamado Misaki Yomiyama perteneciente a la clase 3-3 de la escuela Yomiyama del Norte, murió repentinamente a mitad del año escolar. Devastados por la perdida, sus compañeros y maestro actuaron como si Misaki todavía estuviese vivo e incluso reservaron un lugar para el en la ceremonia de graduación. Lo que fue aún más elocuente, fue que Misaki apareció en la fotografía de la graduación.', '2010', 'Finalizado', '1603262745032_compress88.jpg', 1),
(40, 'dr.jpg', 'Dr. Stone', 'Senku es un joven extremadamente inteligente con un gran don para la ciencia y una Ácida personalidad, y su mejor amigo es Taiju, que es muy buena persona pero más apto para usar los músculos que para pensar. Cuando tras cierto incidente toda la humanidad acaba convertida en piedra, ellos logran despertarse en un mundo miles de años después, con la civilización humana completamente desaparecida y con toda la humanidad congelada en piedra como ellos estuvieron. Ahora es su obligación rescatar a la gente y crear un nuevo mundo.', '2019', 'Finalizado', 'stone.jpg', 1),
(41, 'jujutsu_kaisen.jpg', 'Jujutsu Kaisen', 'Yuuji Itadori es un estudiante de instituto con unas habilidades físicas excepcionales. Todos los días, como rutina, va al hospital a visitar a su abuelo enfermo y decide apuntarse al club de ocultismo del instituto para no dar un palo al agua Sin embargo, un buen día el sello del talismán que se hallaba escondido en su instituto se rompe, y comienzan a aparecer unos monstruos. Ante este giro de los acontecimientos, Itadori decide adentrarse en el instituto para salvar a sus compañeros. ¿Qué le deparará el destino?', '2020', 'En Emisión', 'jujutsu.jpg', 1),
(42, 'tate-no-yuusha-no-nariagari-theme-wb2.jpg', 'Tate No Yuusha', 'Naofumi Iwatani fue invocado en un mundo paralelo junto a otras tres personas para convertirse en los heroes de ese mundo. Cada uno de los heroes fue equipado con su propia arma legendaria cuando fueron convocados. Naofumi recibio el Escudo, el unico equipo defensivo, mientras que los otros recibieron armas capaces de atacar. Debido a la falta de carisma y experiencia, Naofumi termina con una sola compañera de equipo. Desafortunadamente, en su segundo dia, fue traicionado, asaltado y acusado falsamente de violacion por dicha compañera.', '2020', 'Finalizado', 'Fecha-de-estreno-y-trÃ¡iler-de-Tate-no-Yuusha-no-Nariagari-destacada-El-PalomitrÃ³n.jpg', 1),
(43, '378271.jpg', 'Naruto', 'La historia de un ninja adolescente hiperactivo, impredecible y ruidoso llamado Naruto Uzumaki, quien aspira a convertirse afanosamente en Hokage, el máximo grado ninja en su aldea, con el propósito de ser reconocido como alguien importante dentro de la misma.', '2007', 'Finalizado', 'H4SHAV4M7FETFJAPPO3X2ESAZQ.jpg', 1),
(44, '3017bc3db78844985f06950bb7080cd7e9ef0c31_hq.jpg', 'High School DxD', 'La historia trata de un chico issei que es transferido a una escuela que recien se volvio mixta (dos generos) issei en su interior tiene un driver que es traido de generacion en generacion el en su interior tiene el poder de un dragon pero el no lo sabe hasta que conoce a rias la mujer mas hermosa de la escuela que resulta ser una demonio iseei conoce a una chica que resulta ser una estudiante de otro colegio pero lo que no sabe es que es un angel caido (angeles que servian a dios pero fueron expulsados) ella ironicamente mata a issei por que dice que si desarrolla el poder sera una molestia pero antes de morir dice que quiere morir sirbiendo a rias, rias aparece de un portal y a issei como no lo pudo salvar lo reencarno como un demonio issei va desarrollando su abilidad y conociendo mujeres que se van enamorando de el.', '2012', 'Finalizado', 'unnamed.jpg', 1),
(45, 'bfecb5b979fe24aaec5ae62c0d48bf4c.jpg', 'High School DxD New', 'Segunda temporada de High School Dxd, Lleva una vida tranquila hasta que una chica, Amano Yuma, le pide una cita. Claro que no se trata de algo normal: la chica es un angel caido que buscaba asesinarlo. Issei queda atrapado en una guerra entre angeles y demonios que viene de tiempos ascentrales.', '2013', 'Finalizado', '601183.jpg', 2),
(46, 'poster.jpg', 'High School DxD Born', 'Tercer temporada de High School DxD, que hara ahora nuestro personaje favorito Issei con la presidenta? Averigualo disfrutando de esta nueva temporada', '2017', 'Finalizado', 'cropped-1366-768-957162-min.png', 3),
(50, 'Charlotte.jpg', 'Charlotte', 'La historia gira entorno a las habilidades especiales que un pequeño porcentaje de chicos y chicas desarrollan en la pubertad. Yuu Otosaka usa su poder sin que nadie lo sepa y lleva una vida bastante normal, con una vida estudiantil común. Ante Él aparece un día una chica llamada Nao Tomori. Debido a su encuentro con ella, el destino de aquellos con poderes especiales quedará al descubierto. Esta es la historia de como aquellos con poderes especiales experimentan la juventud.', '2015', 'Finalizado', 'charlotte_1.jpg', 1),
(47, 'd5Ddv3OR6afzwzTvEcOnwS9RsZ1.jpg', ' High School DxD Hero', 'Cuarta temporada de High School DxD, despues de todas las batallas nuestros demonios al fin han sido reconocidos en el inframundo, que sucedera en el torneo? Quedate a vivir esta nueva historia', '2018', 'Finalizado', 'u8QK47ttafn3iYox9o1dKyEEhcv.jpg', 4),
(49, 'shippuden.jpg', 'Naruto Shippuden', 'Pasados dos anos y medio de entrenamiento con Jiraiya, Naruto Uzumaki regresa a la aldea oculta de la hoja, donde se reune con sus viejos amigos y conforma de nuevo el Equipo 7. Debido a la ausencia de Sasuke, aparece un nuevo personaje llamado Sai el cual retoma su lugar. En esta secuela podremos notar como los companeros de Naruto han madurado con respecto a su desempeno y la aparicion de la organizacion akatsuki dara un gran giro a la historia...', '2017', 'Finalizado', 'shipuddenbg.jpg', 2),
(48, '1.jpg', 'Kimetsu No Yaiba', 'Estamos en la era Taisho de Japon. Tanjiro, un joven que se gana la vida vendiendo carbon, descubre un dia que su familia ha sido asesinada por un demonio. Para empeorar las cosas, su hermana menor Nezuko, la unica superviviente de la masacre, ha sufrido una transformacion en demonio. Destrozado por los acontecimientos Tanjiro decide convertirse en un cazador de demonios para poder devolver a su hermana a la normalidad y matar al demonio que masacre a su familia.', '2019', 'Finalizado', 'cvhjkfghjfghd.png', 1),
(51, 'hentai-poster.jpg', 'Hentai Ouji to Warawanai Neko', 'Youto Yokodera es un estudiante de instituto que está¡ más salido que el pico de una mesa, pero cada vez que demuestra lo pervertido que es, sus acciones son malinterpretadas y parecen actos de lo más puros. Sin embargo, Youto está harto de tener esta buena prensa y quiere que lo consideren el marrano que es. Un buen día se entera de que hay una estatua de un gato al cual si se le hace una ofrenda, tus deseos se cumplirán, así­ que Youto le ofrece uno de sus objetos más preciados: una dakimakura. Mientras pide su deseo, se encuentra con una chica en el mismo lugar, Tsukiko Tsutsukakushi, la cual viene a pedir a la estatua que quiere dejar de sentirse obligada a expresar sus sentimientos en cada ocasión, porque cree que eso la hace parece más infantil. Y así­, los dos comienzan su nueva vida tras haber pedido sus deseos.', '2013', 'Finalizado', 'fondo.webp', 1),
(52, 'akama ga kill.jpg', 'Akame ga kill ', 'La historia nos lleva a través de las aventuras de Tatsumi, un joven boxeador que viaje a la capital imperial para unirse al ejército. Sin embargo, descubre que la ciudad está dañada por el ansia de poder de los funcionarios, que se aprovechan de la falta de experiencia del emperador para gobernar a su antojo. Después de tener cierto encuentro, Tatsumi se encuentra involucrado dentro de un grupo de asesinos en la sombra llamados \"Night Raid\", luchando contra la tiranía de la Ciudad Imperial...', '2010', 'Finalizado', 'Akame_ga_Kill 2.png', 1),
(53, 'Darling in the Franxx.jpg', 'Darling in the Franxx', 'Los chicos sueñan con poder volar algún día por el infinito cielo, aunque son dolorosamente conscientes de cuán lejos está el cielo más allá del cristal que les impide salir volando. En un futuro distante la humanidad ha creado Plantación, una ciudad fortaleza móvil construida sobre las ruinas del mundo y en la que ha florecido la civilizacion. En la ciudad hay barracones especiales para pilotos llamados Mistilteinn, aunque popularmente se los conoce como \"jaulas de pajaros\". Allá­ es donde viven estos chicos... sin saber nada del mundo exterior, sin poder sentir nunca el enorme cielo. Su Única misión en la vida siempre fue luchar. Sus enemigos son los misteriosos organismos gigantes conocidos como Kyoryu, a los cuales enfrentan con los robots llamados FRANXX. No saben hacer otra cosa y no se lo plantean, pues creen que este es su propósito Único en la vida. entre ellos está un niño al que en su día consideraron un niño prodigio: Codigo 016, Hiro. Sin embargo, ahora es un fracaso y se lo considera innecesario. Quienes no pueden pilotar un FRANXX es como si no existieran. Un día aparece ante Hiro una chica llamada Zero Two y de su cabeza surgen dos cuernos. \"Te encontre, cariño mi­o\"', '2018', 'Finalizado', 'Darling_in_the_Franxx_1.jpg', 1),
(55, 'kaguya.jpg', 'Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen', '¡Todo vale en el amor y en la guerra! Dos genios. Dos cerebros. Dos corazones. Una batalla. ¿Quién declarara primero su amor?! Kaguya Shinomiya y Miyuki Shirogane son dos prodigios de gran inteligencia y quienes controlan el consejo de estudiantes de su prestigiosa academia, lo que las convierte en la carme de la carme de la Élite. Pero claro, estar en la cima es algo que incluye una buena dosis de soledad como extra, y ambos acaban enamorándose el uno del otro. ¿El problema? Que ambos son demasiado orgullosos como para admitir que están enamorados, así­ que el primero que lo admita, Será¡ el perdedor! Comienza su batalla diaria para intentar forzar al otro a declararse primero.', '2019', 'Finalizado', 'sama.jpg', 1),
(56, 'kaguya 2.jpg', 'Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen Temporada 2', 'Segunda temporada de Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen.', '2020', 'Finalizado', 'sama 2.jpg', 2),
(57, 'Dororo.jpg', 'Dororo', 'Daigo Kagemitsu es un temible samurái que entrega su futuro hijo a demonios, a cambio de ver cumplido su sueño de conquistar el paí­s. Al cabo del tiempo, nacía un niño deforme, al que faltaban cuarenta y ocho partes de su cuerpo. Su ambicioso padre lo arroja al río, pero el pequeño logra sobrevivir y, con el tiempo, convertirse en un diestro espadachí­n llamado Hyakkimaru, pequeño monstruo. Años después, con la ayuda del joven y avispado Dororo, quien afirma ser el mejor ladrón de Japón, Hyakkimaru emprenderá un viaje a lo largo del cual se enfrentará¡ a los demonios para recuperar las partes de su cuerpo.', '2019', 'Finalizado', 'Dororo_1.jpg', 1),
(58, '9gzkpjs6N7Xxo1CnnJqhFtmYCez.jpg', 'Dragon Ball Super', 'La trama de la serie tiene lugar después de la batalla contra Pequeño Buu en medio del período de 10 años hacia el Torneo Mundial de las Artes Marciales 28. Está¡ enlazada con las pelí­culas Dragon Ball Z: La Batalla de los Dioses y Dragon Ball Z: La Resurrección de F. La historia comienza a finales del Año 774, seis meses después de la derrota de Buu. La actual saga de Trunks del Futuro Alternativo ocurre el Año 780.', '2015', 'Finalizado', 'fondo.jpg', 1),
(59, 'mnemosyne.jpg', 'Mnemosyne', 'Rin Asougi parece una ordinaria chica de oficina, pero ella es en realidad una investigadora privada que toma cualquier caso, desde encontrar un gato vago hasta infiltrarse en un laboratorio corporativo de alta seguridad. Que es más, ella parece literalmente indestructible, curando sobrenaturalmente cualquier herida y mutilaciones. Juntos con su compañera Mimi, Rin se adentra en los secretos mas oscuros de la sociedad pero los que ella oculta son lejos, mucho más siniestros...', '2008', 'Finalizado', 'MNE.jpg', 1),
(60, 'Kanojo-Okarishimasu.jpg', 'Kanajo, Okarishimasu ', 'En Japón, los solitarios tienen una nueva opción; Aun servicio online para rentar padres, hijos, e incluso novias! Cuando el amor platónico de Kazuya lo rechaza, El decide que está lo suficientemente desesperado para probar el servicio, y queda impactado cuando descubre lo hermosa que es su novia de alquiler. No obstante, ella quiere mantener su relación como un secreto, y hay un problema ella asiste a su universidad y sus abuelas viven en la misma casa ¡y ellos son vecinos! Para su desgracia, Kazuya descubrirá que ella no es tan genial como aparenta', '2020', 'Finalizado', 'kanojo-okarishimasu 1.jpg', 1),
(104, 'anime-attack-on-titan-season-3-P2-visual.jpg', 'Shingeki No Kyojin: The final season', 'El titan siguia buscando la libertad en todas las epocas. Lucho por la libertad. El nombre es: Attack on Titan. La verdad fuera de los muros finalmente fue revelada, y tambien la identidad de los titanes. Hasta este punto, la humanidad estaba haciendo demasiados sacrificios. Sin embargo, debe seguir avanzando. No he visto el mar fuera de la muralla, un simbolo de libertad que debo ver con mis propios ojos. El tiempo sigue su marcha y han pasado 6 años desde el primer ataque de los titanes. El Cuerpo de Exploración sale a expediciones fuera del Muro María. Hay un mar después del muro, y detras del mar hay libertad. Siempre lo crea. El mar, a donde llega la humanidad por primera vez ¿Hay libertad mas alla del horizonte? La historia de Eren Jaeger entra a una nueva fase.', '2020', 'En Emisiòn', 'mikasa-ackerman-shingeki-no-kyojin-battle.jpg', 4),
(61, 'fuku.jpg', 'Fukubiki Triangle 18', 'Después de haber llegado por fin, junto con Miharu, Ushio lleva una vida sexual saludable todos los días. Que llega a su fin un dá, cuando Miharu tiene una caí­da en el camino a la escuela y es hospitalizado. Junto con la hermana de Miharu, Futaba, Ushio la mantiene vigilia en el hospital hasta que Miharu finalmente despierta. Sin embargo, lo hace sin ningún tipo de memoria de Ushio! No salío eso, ella ya no es el alegre y positiva, a Miharu, Ushio no le es familiar. En cambio, este Miharu malhumorado. Futaba revela que este fue el Miharu del pasado, antes de conocer a Ushio. Mientras que Ushio esta preocupado por qué hacer, se da cuenta de la respiración pesada de Futaba, las mejillas encendidas, y la lujuria en los ojos vueltos hacia arriba. A pesar de su preocupación acerca de Miharu, su voluntad se desmorona ante la seducción de Futaba.', '2020', 'En Emisión', 'triangle.jpg', 1),
(62, 'zombi.jpg', 'Zombie Land Saga', 'En abril de 2008, una chica llamada Sakura Minamoto va a enviar una solicitud por correo a una audición de idols que se realizará¡ en Tokio. Desafortunadamente, un camión la arrolla en la puerta de su casa.\r\n\r\nEn el año 2018, Sakura repentinamente despierta sin memoria en una casona de estilo occidental y es atacada por un grupo de zombis y huye del lugar, pero se da cuenta de que también era una zombie. Aparece en escena Kátaro Tatsumi, como un productor del \"Proyecto Zombie Land Saga\", quien busca salvar la prefectura de Saga.\r\n\r\nJunto a otras seis chicas \"legendarias\" de diversas épocas de la historia de Japón comenzarón actividades para crear conciencia sobre la prefectura de Saga, bajo la agrupación de chicas idols zombis denominada \"Franchouhou\".', '2018', 'Finalizado', 'land.png', 1),
(63, 'tt2 v.jpg', 'Tokyo Ghoul √A', 'SECUELA.\r\nSegunda temporada de Tokyo Ghoul.\r\n\r\n', '2017', 'Finalizado', 'tt2.jpg', 2),
(64, 'Anime.webp', 'Prison School', 'La preparatoria femenina Hachimitsu es conocida por sus estándares academicos muy rigurosos. Pero este año, la academia permite que puedan ser admitidos chicos. los 5 chicos logran entrar a la escuela, entre ellos Fujino Kiyoshi. Todos son optimistas y dicen que esta es una oportunidad en la vida de lograr acercarse finalmente a una chica, pero las cosas toman un giro diferente.', '2015', 'Finalizado', 'prison-school.jpg', 1),
(65, 'tk re.jpg', 'Tokyo Ghoul : Re', 'Dos años después del ataque del CCG al Anteiku, la ciudad de Tokio cambia drásticamente debido a la influencia del CCG. Además, los ghouls siguen siendo un problema, pues ahora se han vuelto más cautos. Sin embargo, se creó la nueva escuadra experimental Quinx para mantenerlos a raya, un grupo liderado por un mitad ghoul, mitad humano.', '2018', 'Finalizado', 'tk re2.jpg', 3),
(66, 're 2 b.jpeg', 'Tokyo Ghoul: Re2', 'SECUELA  Tokyo Ghoul:re.\r\nSegunda temporada de Tokyo Ghoul:re\r\n\r\n', '2018', 'Finalizado', 're 2.png', 4),
(67, 'maou.jpg', 'Maou Gakuin No Futekigousha', 'A pesar de su apetito por la destrucción, ¡incluso los reyes demonio se cansan de la sangre y el caos en algunas veces! Cuando Anoth reencarna con la esperanza de una vida más pacífica, termina yendo a una escuela con sus descendientes en su viejo castillo 2,000 años después. Pero con la magia desapareciendo en esta nueva era, y Anoth conservando la suya, ¡¿quién podrá hacerle frente?!\r\n\r\n', '2020', 'Finalizado', 'gakuin.jpg', 1),
(68, 'boruto-naruto-next-generations.jpg', 'Boruto: Naruto Next Generations', 'Esta es una secuela de las series de Naruto, la cual sigue la historia de Boruto el hijo de Naruto. La aldea oculta de la hoja ha continuado su moderinización pero siempre manateniendo la paz. Carros electricos recorren toda la ciudad conectada por distritos llenos de rascacielos con enormes monitores mostrando todo tipo de imagenes. En esta era, la aldea oculta de la hoja es ahora una cuidad ninja solo en nombre ya que ahora muchas personas normales han venido a vivir aqui­. Tambien el estilo de vida de los ninjas ha cambiado... Boruto, el hijo del septimo Hokage y el actual lider de la aldea, se ha matriculado en la academia ninja para aprender todo sobre lo que necesita saber en las artes ninjas. Los estudiantes que rodean a Boruto se refieren a el como \"el hijo del Hokage\", pero Boruto con su peculiar personalidad se hara un nombre por el mismo. Boruto encontro nuevos amigos y aliados, podra lidear con todos esos misteriorsos incidentes que se le presentaran Es asi como comienza la historia de Boruto Uzumaki.', '2019', 'En Emisión', 'borutobg.jpg', 3),
(69, '61855417897fb7e9c8b371f181de8c54.jpg', 'Shingeki no kyojin ', 'Shingeki no Kyojin conocido tambien como Attack on Titan anime de accion, post apocaliptico, drama, suspenso, ciencia ficcion y misterio su increi­ble historia que te deja en cada episodio con ganas de saber mas y mas es la razon por la cual yo se los recomiendo.', '2013', 'Finalizado', 'shingeki-no-kyojin-wallpaper-wallpaper-1-min-min.jpg', 1),
(70, 'attack_on_titan-temporada_2-min.jpg', 'Shingeki no kyojin Temporada 2', 'Pese a sus previas victorias, la humanidad sigue corriendo peligro porque los titanes han atravesado la Muralla Rose. Y por si fuera poco, ha aparecido un nuevo tipo de titan en las inmediaciones...', '2017', 'Finalizado', '2535239-attack-on-titan-wallpapers-min.jpg', 2),
(71, 'evangelion.jpg', 'Neon Genesis Evangelion', 'Segun cuentan los libros de historia, el 13 de Septiembre del 2000, un enorme meteorito choco contra la Antartida, causando el derretimiento del Polo Sur y la consecuente inundacion y destruccion de todas las ciudades costeras. A este evento crucial se lo denomino Segundo Impacto -El primero fue el que destruyo a los dinosaurios-. La Tierra atraveso luego de ello un estado de crisis y catastrofes naturales y mas de mitad de la poblacion humana murio. Han pasado 15 años desde el Segundo Impacto cuando Tokyo-3, es atacada por un misterioso ser organico gigante, sin embargo esto no parece ser una sorpresa para un selecto grupo de gente de una organizacion de la ONU llamada NERV. Ellos se refieren al enemigo como \"Tercer angel\" y han desarrollado unos enigmaticos robots gigantes llamados EVA con una particularidad, solo pueden ser piloteados por jovenes de 14 años con caracteristicas no del todo claras.', '1996', 'Finalizado', 'evangelionbg.png', 1),
(72, 'shingeki-no-kyojin-temporada-3-anime-728x1000.jpg', 'Shingeki no Kyojin Temporada 3', 'Tercera temporada de Shingeki no Kyojin', '2019', 'Finalizado', 'Shingeki no Kyojin Season 3 mega mf gd HD full HD online SoAnimesiteHD4.jpg', 3),
(73, 'renai boukun.jpg', 'Renai Boukun', 'La historia de esta comedia romantica comienza cuando Gris, una angel quien posee un misterioso objeto con el cual puede convertir a dos personas que se besen en una pareja sin importar las circunstancias, aparece frente a Seiji Aino, un joven estudiante Accidentalmente, Gris utiliza su misterioso objeto en el, por lo que se vera obligada a convencer a Seiji de besar a Akane Hiyama, la chica mas popular de su escuela y por la quien el se siente enamorado, ya que de lo contrario ella morira. Sin embargo, la verdadera personalidad de Akane resultara ser un tanto distinta a lo que el se podra haber imaginado.\r\n', '2017', 'Finalizado', 'Renai-Boukun-Portada-.jpg', 1),
(74, 'Uzaki.jpg', 'Uzaki-chan wa Asobitai!', 'Shinichi Sakurai solo desea un poco de paz y silencio en su vida. pero Hana Uzaki (su ruidosa y bien desarrollada kouhai) tiene otros planes. Todo lo que ella quiere es pasar el rato con al y molestarlo un poco. Con la ayuda de su encanto e insistencia, este podr­a ser el inicio de una hermosa relacion!', '2020', 'Finalizado', 'Uzaki-chan-wa-Asobitai-1.jpg', 1),
(75, 'ReLIFE-featured.jpg', 'ReLife', 'La historia esta protagonizada por Arata Kaizaki, un hombre de 27 años, soltero y desempleado al que sus padres le dejan sin apoyo financiero. Incapaz de encontrar trabajo debido a que siempre abandono sus empleos anteriores en menos de tres meses, no sabe que hacer. Una noche, tras estar bebiendo con un viejo amigo del instituto, Arata conoce a Ryo Yoake, un hombre que le ofrece a Arata una pastilla que lo convertira nuevamente en un adolescente de 17 años y asi poder rehacer su vida. Tras acceder a hacer la prueba, Arata se une a una nueva clase en el instituto y conoce a Chizuru Hishiro, una preciosa chica pero muy silenciosa que anhela tener amigos. Arata tendra que interactuar con la chica y el resto de sus nuevos compañeros de clase para descubrir que le falta en su vida para ser feliz en el año que durara el efecto de la pastilla.', '2016', 'Finalizado', 'relifebg.jpg', 1),
(76, 'Shinmai_Maou_no_Testament.jpg', 'Shinmai Maou no Testament', '\"Oye, dijiste que querias una hermana menor, no?\" El padre de Toujo Basara, estudiante de primer año de preparatoria, se lo pregunta sorpresivamente haciendolo caer en panico. Encima de eso, el excentrico padre le dice que se ha vuelto a casar. El entonces viaja al extranjero despues de llevarle a Basara 2 hermosas hermanastras. Las cosas no son lo que aparentan en esta serie, asi es como Basara descubre que su nueva \"familia\" tiene algunos secretos que debe averiguar.', '2013', 'Finalizado', 'Shinmai_Maou_no_Testament_bg.jpg', 1),
(77, 'shinmai_burst.jpg', 'Shinmai Maou no Testament Burst', 'Segunda temporada de Shinmai Mou No Testament, ¿que ocurrira ahora con nuestro Heroe y la Hija del Rey demonio?', '2015', 'Finalizado', 'Shinmai-Maou-no-Testament-BURST.jpg', 2),
(78, 'masou_gakuen_hxh.jpg', 'Masou Gakuen HxH', 'La historia gira en torno a Kizuna Hida, que visita la academia de defensa estrategica Ataraxia a peticion de su hermana mayor. Alli conoce a Aine Chidorigafuchi, una chica que pilota la armadura magica Zerosu. De repente, Aine se desnuda delante de Kizuna.¡No mires, pervertido! le dice Aine, a lo que el protagonista contesta ¡No, eres tabla. Sin embargo, una comunicacion sobre una mision importante llega de la hermana mayor de Kazuna. Esta mision es frotar los pechos de Aina. De hecho, Kizuna resulta tener el poder de aumentar el nivel de una chica de esa forma. Con una batalla que les enfrentara ¡a otro mundo, el futuro depende de su poder.', '2016', 'Finalizado', 'masou_gakuen_hxh_bg.jpg', 1),
(81, 'death-note.jpg', 'Death Note', 'Light Yagami es un excelente estudiante japones que ha tenido una vida aburrida. Esto cambia radicalmente cuando encuentra tirado en el suelo un cuaderno conocido como Death Note (Libreta de la Muerte), un cuaderno perdido por Ryuk, un Shinigami (Dios de la muerte). Cualquier humano cuyo nombre esta escrito en el cuaderno morira, y ahora Light ha decidido utilizar este poder para crear un mundo perfecto sin criminales. Pero cuando los criminales comienzan a morir de forma masiva, las autoridades envian al legendario detective L en busca del asesino. Con L pisandole los talones, Podra mantener Light su noble proposito incluso arriesgando su vida.', '2006', 'Finalizado', 'death-notebg.jpg', 1),
(79, 'asterick_war.jpg', 'Gakusen Toshi Asterisk', 'En el siglo pasado, la humanidad fue atacada por un desastre sin precedentes... el impacto invertiria, el mundo fue completamente destruido. Sin embargo, los humanos adquirieron un nuevo poder: el Genestella', '2016', 'Finalizado', 'asterickbg.jpg', 1),
(80, 'asterick_war2.jpg', 'Gakusen Toshi Asterisk Temporada 2', 'Invertia, la catastrife astral que aniquilo muchas ciudades en el siglo XX, supuso tambien el nacimiento de una nueva raza de humanos con habilidades especiales: los Genestella. Al mismo tiempo, se encontro un elemento especial en el interior del meteoro, \"mana\", que ayuda a que la humanidad diera un salto tecnoligico. En Rikka, la ciudad academica sobre el agua, el \"Asterisk\" como muchos la llaman, estudiantes de seis escuelas se preparan para un torneo que se celebra anualmente y que enfrenta a los mejores estudiantes. Ayato Amagiri, de la Academia Seidoukan, se enfrentara al reto acompañado de Julis, la Bruja de las Llamas Resplandecientes.', '2017', 'Finalizado', 'asterick_bg2.jpeg', 2),
(82, 'nogamenolife.jpg', 'No Game No Life', 'La historia esta protagonizada por Sora y Shiro, hermano y hermana, que son muy famosos en todo Internet como NEETs y hikikomoris que se pasan el dia jugando a videojuegos, tanto que son una leyenda. Los dos consideran el mundo real como un juego malo. Un dia, un chico llamado Dios les invoca a otro mundo. Alli, Dios ha prohibido las guerras y declara que en el mundo todo se decidira mediante juegos, incluso cuales seran las fronteras entre paises. La humanidad se ha visto reducida a una sola ciudad debido a que el resto de razas le han ido quitando todo el territorio. Shiro y Sora tendran que ser los salvadores de la humanidad en este mundo alternativo.', '2018', 'Finalizado', 'NoGamenoLifebg.jpg', 1),
(83, 'hunter-x-hunter-season-5-1-1280x720-1.jpg', 'Hunter x Hunter', 'Hunter x Hunter ests ubicado en un mundo donde existen cazadores para realizar todo tipo de tareas peligrosas, como capturar criminales y buscar valientemente tesoros perdidos en territorios desconocidos. Gon Freecss, de doce años de edad, esta decidido a convertirse en el mejor Cazador posible con la esperanza de encontrar a su padre, que era un Cazador y habi­a abandonado hace mucho tiempo a su hijo pequeño.\r\n\r\nSin embargo, Gon pronto se da cuenta de que el camino para lograr sus objetivos es mucho mas desafiante de lo que jamas hubiera imaginado.', '2011', 'Finalizado', '4wz6-900x600.jpg', 1),
(84, 'hitori.png', 'Hitori Bocchi', 'Hitori Bocchi es una chica que sufre de una tremenda ansiedad social y solo logra hacer una amiga en toda la primaria. Cuando Bocchi descubre que se separare de ella al graduarse, hace una promesa a su preocupada amiga: \"Cuando llegue la graduacion de secundaria habra logrado hacerme amiga de todos mis compañeros de clase\". Pero claro, su amiga le pone una condicion: si no lo logra, ¿dejara de ser su amiga?! El problema es que a Bocchi le cuesta mucho hablar con la gente, y cuando lo intenta le dan calambres en las piernas, se pone nerviosa, ¡y no puede ni mirar a nadie a la cara!', '2013', 'Finalizado', 'bocchi.png', 1),
(85, '51kWhJ4JvhL._SL1200_.jpg', 'Yosuga no Sora', 'Un par de hermanos gemelos, \"Haruka\" y \"Sora Kazugano\" quienes despues de perder a sus padres tienen que mudarse con sus abuelos a la villa donde viven. Sin embargo, hay una razon mas para regresar a ese lugar donde pasaron su infancia, una promesa que se hicieron hace mucho tiempo y un objeto perdido que parece ser importante...', '2010', 'Finalizado', 'haruka-and-yosuga-no-sora-24686639-1280-720.jpg', 1),
(86, '6f843c45497ed5c419e1e34cfa344973-min.jpg', 'Watashi ni Tenshi ga Maiorita!', 'La historia se centra en Miyako Hoshino, una timida estudiante universitaria y otaku . La hermana menor de Miyako, Hinata, que cursa el quinto grado, tiene una compañera de clase y amiga llamada Hana. Cuando se encuentran, Miyako se enamora de Hana a primera vista...', '2019', 'Finalizado', 'Watashi-ni-Tenshi-ga-Maiorita-WATATEN_-an-Angel-Flew-Down-to-Me-Wallpaper-500x355.webp', 1),
(88, 'plastic memoris.jpg', 'Plastic Memories', 'La historia toma lugar en un futuro no muy lejano cuando los androides que parecen exactamente iguales a los humanos comienzan a esparcirse por el mundo. La compañia fabricadora de androides, SA Corp. creo a Giftia, un nuevo tipo de androide que tiene la mayor cantidad de emociones y caracterasticas humanas hasta el momento. Sin embargo, debido a problemas tecnologicos, los androides tuvieron una vida de servicio, y una vez que pasan esto, ellos Bueno, las cosas se ponen feas. Para esto, SA Corp. crea un servicio de terminal para recuperar a los Giftia que han cumplido con su vida de servicio. Un nuevo empleado en el terminal llamado Tsukasa Mizugaki forma un equipo con el Giftia Isla para recuperar a los otros androides.', '2015', 'Finalizado', 'Plastic-Memories-1.jpg', 1),
(89, 'vivd-strike-new-key.jpg', 'ViVid Strike!', 'Fuuka y Rinne son dos niñas que viven en un orfanato. Son viejas amigas de la infancia y son casi como hermanas. Estas dos niñas viven dia a dia soñando con el futuro mientras soy muy pobres. Sin embargo, cuando Fuuka y Rinne son visitadas por las \"dos partes\", de repente sus destinos comienzan a cambiar...', '2016', 'Finalizado', 'Vivid_00_25.jpg', 1),
(90, '56f3181ed883c362a51ed4053983dd46.jpg', 'Tower of God', 'Alcanza la lo mas alto y todo sera tuyo. En la cima de la torre encontraras todo lo que existe en este mundo, y todo puede ser tuyo. Podras ser un dios. Esta es la historia del inicio y el final de Rachel, la joven que ascendio la torre para poder ver las estrellas, y Bam, el joven que lo unico que necesitaba era estar con ella. ', '2020', 'Finalizado', 'tower-of-god.jpg', 1),
(91, 'THE GOD OF HIGH SCHOOL.jpg', 'The God of High School', 'Jin Mori se ha autoproclamado como el estudiante de preparatoria mas fuerte del mundo, pero su vida cambia por completo cuando lo invitan a participar en el \"God of High School\", un torneo en el que se decidira el estudiante mas fuerte de todos. Para convencerlo para participar le dicen que si gana podra pedir cualquier deseo... Todos los participantes son fuertes contrincantes dispuestos a todo para ganar y cumplir sus deseos.', '2020', 'Finalizado', 'THE GOD OF HIGH SCHOOL 1.jpg', 1),
(92, 'Love Live.png', 'Love Live!', 'La historia se desarrolla en Uchiura, una ciudad costera situada cerca de Numazu, a 130 kilometros de Tokio. Con el fin de darle vida al pequeño Instituto al que asisten, que solo tiene 100 estudiantes, las nueve protagonistas formaran un grupo de School Idols Centrada en la Preparatoria Otonokizaka la cual esta en riesgo de cerrarse debido al numero reducido de estudiantes. Para evitarlo, las chicas se volveran idols para promocionar su escuela.', '2013', 'Finalizado', 'Love Live 1.jpg', 1),
(93, 'Love Live tem 2.jpg', 'Love Live! 2', 'Una escuela situada entre los barrios japoneses de Akihabara, Kanda y Jinbocho en Tokio. Este centro se encuentra en peligro de ser cerrado por lo que nueve estudiantes femeninas luchan por convertirse en idols para dar fama a su escuela y aumentar la asistencia.', '2014', 'Finalizado', 'Love-Live temp 2.jpg', 2),
(94, 'Fire force.jpg', 'Enen no Shoboutai ', 'Tokio se encuentra bajo un extraño fenomeno: ¡la gente entra, sin remedio, en combustion espontenea! Aunque, afortunadamente, hay un equipo a cargo de mantener a raya este particular infierno ¡Fire Force! Que, ademas, ahora cuenta con un nuevo miembro: Shinra, un adolescente de sonrisa perturbadora, poder curioso y cuyo objetivo es convertirse en un heroe.', '2015', 'Finalizado', 'Fire force 1.jpg', 1),
(95, 'Kamisama ni natta hi.jpg', 'Kamisama ni Natta Hi ', 'Yota Narukami es un estudiante de secundaria que planeaba pasar sus ultimas vacaciones de verano como la mayori­a de los demas: preparandose para sus examenes de ingreso a la universidad. Pero cuando una joven llamada Hina se le acerca y le dice que es un dios, sus vacaciones de verano de repente se vuelven todo menos normales.', '2020', 'En Emisión', 'Kamisama ni natta hi 1.jpg', 1),
(96, 'noblesse (1).jpg', 'Noblesse', 'Noblesse trata de un poderoso noble, Cadis Etrama Di Raizel (conocido como Rai), que ha estado dormido durante 820 años sin conocer el avance de la humanidad y los exitos cientificos... Noblesse sigue las a menudo peligrosas aventuras del grupo contra una organizacion secreta mientras descubre el pasado de Rai.', '2020', 'En Emisión', 'Noblesse-1.jpg', 1),
(97, 'sin-nanatsu.JPG', 'Sin Nanatsu No Taizai', 'El contexto de la franquicia gira en torno a siete feminas que encarnan los siete pecados capitales: lujuria, pereza, gula, ira, envidia, avaricia y soberbia. La Angel Caido Lucifer hara su aparicion para controlar a los pecados y el inframundo entero, despues de ser desterrada del cielo.', '2017', 'Finalizado', 'sin-nanatsubg.jpg', 1),
(98, 'Hitori_no_Shita_the_outcast-cover.jpg', 'Hitori No Shita: The Outcast', 'El protagonista, Cho Soran, lleva una vida de estudiante muy normal hasta que se ve involucrado en un terrible incidente que ocurre en un pequeño pueblo. Segun pasaba por el cementerio, Cho se ve asaltado por unos zombis, y pensando que van a por al, una misteriosa chica con una espada le salva y desaparece de repente. Este extraño encuentro cambiara por completo el destino de nuestro heroe.', '2019', 'Finalizado', 'maxresdefault.jpg', 1),
(99, 'Ore monogatari.jpg', 'Ore Monogatari!!', 'La historia sigue a Takeo \"Muri\" Goda, un estudiante alto y musculoso que no tiene mucha suerte con las mujeres debido a que cada chica que le gusta termina enamorandose de su mejor amigo, Makoto Sunakawa, quien es encantador y apuesto. Todo esto cambia cuando salva a Rinko Yamato, una chica timida y pequeña que, por encima de otras expectativas, se enamora de Takeo, a partir de ahi­ comienza una historia de amor unica diferente a cualquier otra.', '2015', 'Finalizado', 'Ore monogatari 1.png', 1),
(100, 'Hitori_no_Shita_the_outcast-2.jpg', 'Hitori No Shita: The Outcast 2', 'Segunda Temporada de Hitori No Shita', '2017', 'Finalizado', '5bc8cc5019f3c.jpg', 2),
(101, 'Hitori-no-Shita-Season-3.jpg', 'Hitori No Shita: The Outcast 3', 'Tercer temporada de Hitori No Shita ', '2020', 'En Emisión', 'Hitori-no-Shita-The-Outcast-3rd-Season-706x410.jpg', 3),
(102, 'gto.jpg', 'GTO: Great To Teacher Onizuka', 'Eikichi Onizuka, 22 aÃ±os, soltero\" esta es la forma en que este peculiar personaje se presenta; con su gran sueÃ±o de ser profesor Onizuka se enfrenta a una serie de problemas, creados por quienes podrÃ­an ser los alumnos mas problemÃ¡ticos para un profesor. Estudiantes que crean a la vez un sinfÃ­n de divertidas situaciones', '2000', 'Finalizado', 'gto2.png', 1),
(103, 'gto1.jpg', 'GTO: GREAT TO TEACHER ONIZUKA  OVAS', 'GTO: GREAT TO TEACHER ONIZUKA\r\nTODOS LOS OVAS 1-5', '2002', 'Finalizado', '7n8ZT8wEnQ0nQrQsFSIpV4FT5ba.jpg', 2);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `animes`
--
ALTER TABLE `animes`
  ADD PRIMARY KEY (`id_anime`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `animes`
--
ALTER TABLE `animes`
  MODIFY `id_anime` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=105;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
